#!/usr/bin/env sh

COMMIT_MSG="$(cat $1)"
COMMIT_MSG_REGEX='^(feat|fix|ref): [A-Z][a-zA-Z]+'

if ! echo "$COMMIT_MSG" | grep -E "$COMMIT_MSG_REGEX" >/dev/null 2>&1; then
  echo "Aborting commit. Your commit message does not match the required format."
  echo "Examples:"
  echo "feat: Added animation transition"
  echo "fix: Debug first page"
  echo "ref: Refactored Shopping page"
  exit 1
fi

exit 0